### ISSUE TITLE
Replace row names of genes by gene1, gene2, etc

### ISSUE THREAD

**Issue by AlineTalhouk** [OVCARE/nanostringr#2]
This is for *_ovarian data only *_and somehow we make sure that the original names cannot be recovered from git history

**Comment by dchiu911** [comment]
So this is for `ovc.r`, `ovd.r`, `ovo.r`?

**Comment by dchiu911** [comment]
Please check cb5d210c4af163854a1004bb124888ce302b41f8 comment
