### ISSUE TITLE
HKnorm behaviour

### ISSUE THREAD

**Issue by dchiu911** [OVCARE/nanostringr#4]
Hi @AlineTalhouk 

I'm reviewing the code for `HKnorm` and noticed some weird behaviour. Would you mind reviewing this commit at your convenience? https://github.com/OVCARE/nanostringr/commit/bf9eed63f53d431b7f482686bd9210708a86fb15#diff-23ed1a4c25ddc957e7918f784cec4b56

Thanks,
Derek

**Comment by AlineTalhouk** [comment]
I just reviewed seems fine. I just allow for possibility of entering log or raw data. What issues are you noticing?

**Comment by dchiu911** [comment]
False alarm!
