### ISSUE TITLE
AppVeyor: Build failed

### ISSUE THREAD

**Issue by AlineTalhouk** [OVCARE/nanostringr#5]
Commit e531e82ac5 by Derek Chiu on 10/4/2016 6:41 PM: 
try adding Travis, AppVeyor, Codecov

**Comment by AlineTalhouk** [comment]
Maybe you saw this..

**Comment by dchiu911** [comment]
No worries, I get email notifications after every build. Debugging now

**Comment by dchiu911** [comment]
Builds and coverage shown on [README](https://github.com/OVCARE/nanostringr) now
